name: local-decoder-4b
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12.13
  - numpy=2.0.2
  - matplotlib=3.7.5
  - pyarrow=18.1.0
  - pytest=8.3.5
  - pytorch=2.6.0
  - pytorch-cuda=12.4

